apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
name: deploy-cm
spec:
inputs:
    resources:
    - name: acmeair-git
        type: git
    params:
    - name: pathToContext
        type: string
        default: /workspace/acmeair-git
    - name: targetNamespace
        type: string
        default: devops-lab
steps:
    - name: oc-service
    image: quay.io/openshift/origin-cli:latest
    env:
        - name: REG_PWD
        valueFrom:
            secretKeyRef:
            name: devops-lab-deployer-secret
            key: token
    command: ["/bin/bash", "-c"]
    args:
        - oc apply -f /workspace/acmeair-git/deployment.yaml --token=$REG_PWD -n $(inputs.params.targetNamespace)
