kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: modresorts-app-twas
  labels:
    app: modresorts-app-twas
spec:
  to:
    kind: Service
    name: modresorts-app-twas
    weight: 100
  port:
    targetPort: 9443-tcp
  tls:
    termination: passthrough
  wildcardPolicy: None
